### ISSUE TITLE
I pasted all of your slides in /usr/share/libreoffice/share/templete/common/present but they doesn't show up in LibreImpress's 'Available for Use' section.

### ISSUE THREAD

**Issue by PranavBhattarai** [FortunEdge/nimble_slides_impress#4]
What to do?
![Screenshot from 2020-04-16 21-04-57](https://user-images.githubusercontent.com/32763112/79475184-11dd0a00-8027-11ea-94dd-8b444d67caca.png)

I want those slides to show up here. But it doesn't show.
```
OS: Ubuntu 19.10
LO: 6.3.5.2
```

**Comment by FortunEdge** [comment]
So sorry I didn't see this issue when you posted. I haven't been monitoring this repo for a while and will be switching it to archived mode so this doesn't happen again.

I presume you've found your solution or taken it up with the LibreOffice folks, but in case someone stumbles on this thread in the future:

Adding templates through the Import dialogue found in ```File > Templates > Manage Templates``` will add them to the "Available for Use" list.

```
OS: elementary OS 5.1.7 (Ubuntu 18.04.4 LTS)
LO: 7.0.2.2
```
